name: di_visualizer_annotation
description: di_visualizer_annotation
version: 0.0.1
homepage: https://github.com/jWinterDay/di_visualizer_annotation

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  j_linter: ^0.0.6